### ISSUE TITLE
Migrate from Digital Ocean to PlanetScale

### ISSUE THREAD

**Issue by tsAppDevelopment** [tsAppDevelopment/buildable#19]
# Why should I?
Using [PlanetScale(PS)](https://planetscale.com/) would be preferable to hosing a single instance of PSQL on Digital Ocean (DO) because:
- PS auto scales to the moon with Vitess 🚀
- PS has DB branching
- PS has better vitals
- PS has better logging
- PS has a much greater connection limit than PSQL and PGBouncer
- DO can has no support for traffic spikes
- My other DBs are on PS

[Prisma and PS write up](https://leerob.io/blog/mysql-planetscale)

# TODO
see: [fullstack-template](https://github.com/tsAppDevelopment/fullstack-template)
- [ ] migrate Prisma from PSQL to MySQL 
- [ ] migrate docker compose to use MySQL
- [ ] migrate npm scripts to use MySQL
<br/>

- [ ] create new PS DB
- [ ] push schema to PS
- [ ] migrate data from DO to PS
- [ ] update Vercel env to point to PS DB
- [ ] delete DO PSQL instance

# Bonus Round
- [ ] setup CI to push schema changes of feature branches to new Planet Scale branches
- [ ] setup CI to push schema changes of master into DB
